import type { MasterManifest } from "./masterStoryHelper";

// Generated by the film pipeline. A missing manifest is a build error rather
// than a silent legacy fallback: the /v2 route must never ship without its cut.
import generatedManifest from "../../film/masterManifest.json";

export const MASTER_MANIFEST = generatedManifest as MasterManifest;
